# Machine Learning and Deep Learning Masters Course by iNeuron.ai

# Python Assignment - 7 NumPy

### Dr. Mahesh Huddar

#### 1. Write a function so that the columns of the output matrix are powers of the input vector.

In [1]:
import numpy as np

x = np.array([1, 2, 3, 5])
np.vander(x)

np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [2]:
def vander_matrix(vector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
        
    elif increasing:
        op_matx = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    
    return op_matx

In [3]:
vector=np.array([1,2,3])

In [4]:
vander_matrix(vector,5)

array([[ 1,  1,  1,  1,  1],
       [16,  8,  4,  2,  1],
       [81, 27,  9,  3,  1]])

In [5]:
vander_matrix(vector,5,True)

array([[ 1,  1,  1,  1,  1],
       [ 1,  2,  4,  8, 16],
       [ 1,  3,  9, 27, 81]])

#### 2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
##### The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [6]:
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def mov_avg(values,window):
    weights = np.repeat(1.0,window)/window
    smas = np.convolve(values,weights,'valid')
    return smas 

In [7]:
print (mov_avg(dataset,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [8]:
print (mov_avg(dataset,4))

[  4.25   5.5    6.75   7.75  23.5   39.5   57.25  79.25  88.   107.5 ]
